version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: y2De9qUw
      POSTGRES_USER: domRU
      POSTGRES_DB: domru

  wordpress:
    image: wordpress:6.2.2
    volumes:
      - ./wp-content:/var/www/html/wp-content
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: domRU
      WORDPRESS_DB_PASSWORD: y2De9qUw  # Измените пароль на новый пароль PostgreSQL
      WORDPRESS_DB_NAME: domru
      WORDPRESS_LANGUAGE: ru_RU
      WORDPRESS_USER: domru
      WORDPRESS_PASSWORD: yYgfN0eH

volumes:
  db_data: